name: NestJs Workflow

on: [ pull_request ]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      NPM_GITHUB_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'

      - name: Yarn install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Unit test
        run: yarn test

      - name: Testing e2e + coverage
        run: yarn test:e2e:cov

      - name: Lib build
        run: yarn lib:build


